<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\PG3302.Domain\PG3302.Domain.csproj" />
    <ProjectReference Include="..\PG3302.Infrastructure\PG3302.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Stripe.net" Version="52.4.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>OrderManager-Web-Stripe-Development</UserSecretsId>
  </PropertyGroup>

</Project>
