services:
  postgres:
    image: postgres:17
    container_name: nordly-postgres
    environment:
      POSTGRES_DB: nordly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - nordly-postgres-data:/var/lib/postgresql/data

volumes:
  nordly-postgres-data: