services:
  - type: web
    name: nordly
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Stripe__SecretKey
        sync: false
      - key: Stripe__WebhookSecret
        sync: false
      - key: Email__SmtpHost
        sync: false
      - key: Email__SmtpPort
        sync: false
      - key: Email__EnableSsl
        sync: false
      - key: Email__Username
        sync: false
      - key: Email__Password
        sync: false
      - key: Email__FromAddress
        sync: false
      - key: Email__FromName
        sync: false
