<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Nordly.Domain\Nordly.Domain.csproj" />
    <ProjectReference Include="..\Nordly.Infrastructure\Nordly.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Stripe.net" Version="52.4.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>Nordly-Web-Stripe-Development</UserSecretsId>
  </PropertyGroup>

</Project>
